---
- name: Login to x-ui and get session cookie
  uri:
    url: "https://localhost:{{ xui_port }}/login"
    method: POST
    headers:
      Content-Type: "application/json"
    body: |
      {
        "username": "{{ xui_username }}",
        "password": "{{ xui_password }}"
      }
    body_format: json
    validate_certs: false
    # ca_path: "./certs/ca.crt"
    return_content: true
  register: login_result

- debug:
    var: login_result

- name: Extract session cookie
  set_fact:
    xui_cookie: "{{ login_result.cookies.session | default('') }}"

- name: Add new inbound via x-ui API using session cookie
  uri:
    url: "https://localhost:{{ xui_port }}/panel/api/inbounds/add"
    method: POST
    headers:
      Content-Type: "application/json"
      Cookie: "3x-ui={{ login_result.cookies['3x-ui'] }}"
    body: |
      {
      "enable": true,
      "remark": "Clients",
      "listen": "",
      "port": 443,
      "protocol": "vless",
      "expiryTime": 0,
      "settings": "{\"clients\":[{\"id\":\"95e4e7bb-7786-47e7-e8a7-f4055194f776\",\"alterId\":0,\"email\":\"Zero Client\",\"flow\": \"xtls-rprx-vision\",\"limitIp\":2,\"expiryTime\":3102278400000,\"enable\":true,\"tgId\":\"\",\"subId\":\"\"}],\"decryption\": \"none\"}",
      "streamSettings": "{\"decryption\": \"none\",\"network\":\"tcp\",\"security\":\"reality\",\"realitySettings\":{\"dest\":\"apple.com:443\",\"privateKey\":\"{{ xray_private_key }}\",\"shortIds\": [\"1be5faa8999f4f\",\"3e442ea3\",\"0ef273d3ee\",\"17eb741a05c2\",\"f69daf9e6394d21f\",\"c9\",\"f09a\",\"862b16\"],\"serverNames\":[\"apple.com\",\"www.apple.com\"],\"settings\":{\"publicKey\":\"{{ xray_public_key }}\",\"fingerprint\":\"random\",\"serverName\":\"\",\"spiderX\":\"/\"}},\"tcpSettings\":{\"acceptProxyProtocol\":false,\"header\":{\"type\":\"none\"}}}",
      "sniffing": "{\"enabled\":true,\"destOverride\":[\"http\",\"tls\"]}"
      }
    body_format: json
    validate_certs: false
    # client_cert: ../certs/{{ inventory_hostname }}/{{ inventory_hostname }}.crt
    # ca_path: ../certs/{{ inventory_hostname }}/
    return_content: true
  register: add_inbound_result

- debug:
    var: add_inbound_result.json