---
- name: Ensure password authentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backrefs: yes

- name: Ensure root login without key is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
    backrefs: yes

- name: Restart SSH to apply changes
  service:
    name: ssh
    state: restarted